# DEVICE_LIST: dict[str, dict[str, bool]] = {
#     'JBL BAR 500': {'manual_refresh': True, 'always_abs_seek': True, 'rel_seek_is_abs': True},
#     'TX-NR737': {'manual_refresh': True, 'always_abs_seek': True, 'rel_seek_is_abs': False},
#     'default': {'manual_refresh': False, 'always_abs_seek': True, 'rel_seek_is_abs': False} 
#    
# }

[default]
name = 'default'
manual_refresh = false
always_abs_seek = true
 # Use absolute seek by dafault because relative seek is a mess
rel_seek_is_abs = false

[JBL_BAR_500]
name = 'JBL BAR 500'
manual_refresh = true
rel_seek_is_abs = true

[TX-NR737]
name = 'TX-NR737'
manual_refresh = true

